spring.application.name=autoshop

#conexão com o banco
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=Gustavo
spring.datasource.password=123123

#configuracao jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#flyway
spring.flyway.baselineOnMigrate=true
